# hal_c2_native: the shell's own half, built once for the app and the native
# tests. Every file in src/native (the MC client, the store, the
# controllers, their models) plus ShellBridge, which they publish through. A new file there is picked up on the next build, no list to
# edit.
#
# themes.json, generated by scripts/gen-themes.mjs, is compiled in as a resource,
# and so are the settings sections (js/settingsPages.js), for the native
# tests' bricks that import them by URL.
#
# A Device tab's H.264 screen is decoded with FFmpeg's libavcodec (and
# scaled with libswscale): QtMultimedia's player paces and buffers by
# timestamp, where a live screen wants every picture as soon as it decodes
# and a keyframe asked for when it falls behind. Only FFmpeg's headers are
# needed to build (found through pkg-config); nothing links or ships it. The
# libraries load at run time (src/native/FFmpeg.cpp), so the app starts
# without them and the Device tab says what to install.
#
# OBJECT, not STATIC: controllers register themselves from static
# initialisers (NativeControllerRegistrar), which an archive would drop.
#
# Include once per project, then link `hal_c2_native`.

function(hal_c2_add_native_library)
  get_filename_component(_hal_c2_src "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../src" ABSOLUTE)
  file(GLOB _sources CONFIGURE_DEPENDS "${_hal_c2_src}/native/*.cpp" "${_hal_c2_src}/native/*.h")
  add_library(hal_c2_native OBJECT ${_sources} "${_hal_c2_src}/ShellBridge.cpp" "${_hal_c2_src}/ShellBridge.h")
  set_target_properties(hal_c2_native PROPERTIES AUTOMOC ON)
  # Its classes as HalC2.Shell declares them to tools (src/ShellQmlTypes.h).
  qt_extract_metatypes(hal_c2_native)
  target_include_directories(hal_c2_native PUBLIC "${_hal_c2_src}" "${_hal_c2_src}/native")
  # The QR codes pairing links are shown as (src/native/QrCode.cpp).
  include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/QrCodeGen.cmake")
  target_sources(hal_c2_native PRIVATE "${qrcodegen_SOURCE_DIR}/cpp/qrcodegen.cpp")
  target_include_directories(hal_c2_native PRIVATE "${qrcodegen_SOURCE_DIR}/cpp")
  # Android has no FFmpeg to load and pkg-config would find this machine's
  # headers, so that build leaves the decoder out (see FFmpeg.h).
  if(NOT ANDROID)
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(HAL_C2_FFMPEG REQUIRED libavcodec libavutil libswscale)
    target_include_directories(hal_c2_native PUBLIC ${HAL_C2_FFMPEG_INCLUDE_DIRS})
    target_compile_definitions(hal_c2_native PUBLIC HAL_C2_HAS_FFMPEG)
  endif()
  # Qt6::Sql is the client cache (src/native/LocalCache.cpp), which needs the SQLite driver at run time.
  target_link_libraries(hal_c2_native PUBLIC Qt6::Core Qt6::Gui Qt6::GuiPrivate Qt6::Qml Qt6::Quick Qt6::Network Qt6::Sql Qt6::WebSockets)
  # The built-in palettes (scripts/gen-themes.mjs), as :/hal-c2/themes.json.
  qt_add_resources(hal_c2_native hal_c2_native_themes PREFIX "/hal-c2" BASE "${_hal_c2_src}/native"
                   FILES "${_hal_c2_src}/native/themes.json")
  # :/hal-c2/settings/settingsPages.js and what it imports.
  set(_hal_c2_js "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../qml/HalC2/Bricks/js")
  qt_add_resources(hal_c2_native hal_c2_native_settings PREFIX "/hal-c2/settings" BASE "${_hal_c2_js}"
                   FILES "${_hal_c2_js}/settingsPages.js" "${_hal_c2_js}/settingsRows.js")
  # Snap Shot's capture sounds, as :/hal-c2/sounds/*.oga.
  qt_add_resources(hal_c2_native hal_c2_native_sounds PREFIX "/hal-c2" BASE "${_hal_c2_src}/native"
                   FILES "${_hal_c2_src}/native/sounds/snap-shot-click.oga" "${_hal_c2_src}/native/sounds/snap-shot-whoosh.oga")
  # Snap Shot's xdg-desktop-portal backend talks D-Bus (PortalSnapShot).
  if(UNIX AND NOT APPLE AND NOT ANDROID)
    find_package(Qt6 REQUIRED COMPONENTS DBus)
    target_link_libraries(hal_c2_native PUBLIC Qt6::DBus)
    target_compile_definitions(hal_c2_native PUBLIC HAL_C2_HAS_DBUS)
  endif()
endfunction()
